=== rgupta00/oracle_induction_sept_oct_25_batch21_code/spring_boot_all/springboot_fullstack/demoxml/schema_demo/orders.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.oracle.com/orders"
	xmlns:tns="http://www.oracle.com/orders" 
		elementFormDefault="unqualified">
	<complexType name="orderItem">
		<sequence>
			<element name="itemId" type="int"/>
			<element name="itemName" type="string"/>
			<element name="quantity" type="int"/>	
		</sequence>
	</complexType>
	<complexType name="orders">
		<sequence>
			<element name="oderId" type="int"/>
			<element name="customId" type="int"/>
			<element name="orderItems" type="tns:orderItem" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	
	<element name="orders" type="tns:orders"/>
</schema>

=== rgupta00/oracle_induction_sept_oct_25_batch21_code/core_java2/xmldemo1/demo3_schema/orders.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:orders xmlns:tns="http://www.oracle.com/orders"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.oracle.com/orders orders.xsd ">
	<oderId>1</oderId>
	<customId>123</customId>
	<orderItems>
		<itemId>121</itemId>
		<itemName>dell laptop</itemName>
		<quantity>1</quantity>
	</orderItems>
		<orderItems>
		<itemId>11</itemId>
		<itemName>laptop laptop</itemName>
		<quantity>1</quantity>
	</orderItems>
</tns:orders>
